import {ledger,simplify,cents} from './money.js';
import {tripCsv,activitySummary} from './formats.js';
const API='https://rxzaoeolvaoafzhofcco.supabase.co/functions/v1/paris-split-api';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(n,c='EUR')=>new Intl.NumberFormat('en-IE',{style:'currency',currency:c}).format(n);
const date=v=>new Date(v).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
let state=null,view='expenses',mode='create',code='',actor='',ws=null,heartbeat=null,reconnect=null,config=null,refreshing=false,toastTimer,epoch=0;
const storage={get(k){try{return localStorage.getItem(k)||''}catch{return ''}},set(k,v){try{localStorage.setItem(k,v)}catch{}},remove(k){try{localStorage.removeItem(k)}catch{}}};
function toast(s){$('#toast').textContent=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',4500);}
function connection(s){$('#connection').textContent=s;}
async function transport(payload){
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);
 try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});const s=await r.json();if(!r.ok||s.error)throw Error(s.error||'Could not complete request');return s;}
 catch(e){if(e instanceof TypeError||e.name==='AbortError')throw Error('Connection interrupted. Retry this save with the same values; it will not be added twice.');throw e;}finally{clearTimeout(timer);}
}
function setTrip(s){
 const old=trips().find(t=>t.id===s.trip.id)||{};
 const record={id:s.trip.id,name:s.trip.name,code:s.trip.invite_code,session:s.session_token||old.session||'',owner:s.owner_key||old.owner||'',actor:s.members.find(m=>m.id===s.current_member_id)?.name||old.actor||''};
 saveTrip(record);state=s;code=record.code;actor=s.current_member_id?record.actor:'';
 delete state.owner_key;delete state.session_token;
 storage.set('paris-code',code);history.replaceState(null,'',location.pathname+'#'+code);render();
}
async function refresh(){if(!state||refreshing)return;refreshing=true;const token=epoch;try{const s=await api({action:'get_trip',invite_code:code});if(token===epoch&&Number(s.activity[0]?.id||0)>=Number(state?.activity[0]?.id||0))setTrip(s);}catch(e){if(/removed|expired|reset|invalid|replaced/i.test(e.message)){leave();toast(e.message);}else connection('Reconnecting…');}finally{refreshing=false;}}
async function live(){
 clearTimeout(reconnect);clearInterval(heartbeat);if(ws){ws.onclose=null;ws.close();}
 if(!state)return;const token=epoch;
 try{config??=await (await fetch(API)).json();if(token!==epoch)return;
 const topic='realtime:paris:'+state.trip.id;let ref=1;
 ws=new WebSocket(config.url.replace('https:','wss:')+'/realtime/v1/websocket?apikey='+encodeURIComponent(config.anonKey)+'&vsn=1.0.0');
 const send=(event,payload,channel=topic)=>ws?.readyState===1&&ws.send(JSON.stringify({topic:channel,event,payload,ref:String(ref++)}));
 ws.onopen=()=>{send('phx_join',{config:{broadcast:{self:false},presence:{key:''},postgres_changes:[],private:false},access_token:config.anonKey});heartbeat=setInterval(()=>send('heartbeat',{},'phoenix'),25000);};
 ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.event==='phx_reply'&&m.ref==='1'){if(m.payload.status==='ok'){connection('● Live with your group');refresh();}else{connection('Syncing every 30 seconds');}}if(m.event==='broadcast'&&m.payload.event==='changed')refresh();}catch{}};
 ws.onclose=()=>{clearInterval(heartbeat);if(token===epoch&&state){connection('Reconnecting…');reconnect=setTimeout(live,3000);}};
 }catch{connection('Syncing every 30 seconds');reconnect=setTimeout(live,5000);}
}
setInterval(()=>{if(!document.hidden)refresh()},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('online',()=>{refresh();live();});
function welcomeBase(){
 $('#app').innerHTML=`<section class="welcome"><div class="intro"><div class="eyebrow">THE PARIS CHAPTER</div><h1>A little less maths.<br>A little more <em>Paris.</em></h1><p>From the first café to the last taxi. Keep shared expenses simple, wherever your friends call home.</p><div class="art" aria-hidden="true"><svg viewBox="0 0 450 200" fill="none" stroke="#68816c" stroke-width="2"><path d="M45 167h360M179 167l20-47 14-60 12-47 12 47 14 60 20 47M200 119h50M209 83h32M214 61h22M188 146h74M205 167q20-40 40 0M225 13V3M85 166v-61h39v61m-47-61 27-27 28 27m177 61v-70h47v70m-54-70 31-25 30 25M92 119h9m10 0h8m-27 16h9m10 0h8m210-23h10m7 0h10m-27 17h10m7 0h10"/><circle cx="333" cy="43" r="20" fill="#edb572" stroke="none"/><path d="M30 184q70-14 140 0t140 0 110 0" stroke="#9cab8d"/></svg><span class="art-label">48.8566° N · 2.3522° E</span></div></div><div class="panel"><div class="tabs"><button data-mode="create" class="${mode==='create'?'active':''}">Start a trip</button><button data-mode="join" class="${mode==='join'?'active':''}">Join friends</button></div><h2>${mode==='create'?'Make room for everyone.':'You’re in good company.'}</h2><p class="muted">${mode==='create'?'One shared place for your trip’s expenses.':'Open your group’s shared trip with its invite.'}</p><form id="welcome-form">${mode==='create'?'<label for="trip-name">Trip name</label><input id="trip-name" name="name" required maxlength="120" value="Paris 2026">':'<label for="invite">Invite link or code</label><input id="invite" name="invite" required autocomplete="off" placeholder="Paste your invite link">'}<label for="your-name">Your name</label><input id="your-name" name="member_name" required maxlength="80" autocomplete="given-name" placeholder="What should we call you?"><div class="error" role="alert"></div><button class="full">${mode==='create'?'Create our trip →':'Join the trip →'}</button><p class="fine">No accounts. Anyone with the invite can view and edit this trip. Share it only with your travel group.</p></form></div></section><section class="feature-strip"><div><b>Four currencies, one clear balance</b><p>EUR, GBP, CAD & USD. Rates stay fixed per expense.</p></div><div><b>Your trip, your way to split</b><p>Equal, shares, percentages or exact amounts.</p></div><div><b>Everyone stays in the loop</b><p>Shared history and live updates across phones.</p></div></section>`;
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;welcome()});
 bindForm($('#welcome-form'),async(f,request_id)=>{
 actor=f.get('member_name').trim();if(!actor)throw Error('Please enter your name.');let s;
 if(mode==='create')s=await api({action:'create_trip',name:f.get('name').trim(),member_name:actor,request_id});
 else{code=parseCode(f.get('invite'));s=await api({action:'join_trip',invite_code:code,name:actor,request_id});}
 epoch++;setTrip(s);live();
 });
}
function parseCode(s){s=s.trim();if(s.includes('#'))s=s.slice(s.lastIndexOf('#')+1);s=s.toUpperCase();if(!/^[A-F0-9]{40}$/.test(s))throw Error('Paste the complete invite link or 40-character code.');return s;}
function bindForm(form,fn){let previous='',request_id='';form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form),body=JSON.stringify([...f]);if(body!==previous){previous=body;request_id=crypto.randomUUID();}const button=form.querySelector('button[type=submit],button:not([type])');const err=form.querySelector('.error');err.textContent='';button.disabled=true;try{await fn(f,request_id);}catch(e){err.textContent=e.message;}finally{button.disabled=false;}};}
function member(id){return state.members.find(m=>m.id===id)?.name||'Member'}
function renderBase(){if(!state)return welcome();const l=ledger(state),own=state.members.find(m=>m.name===actor),balance=l.balances[own?.id]||0;
 $('#app').innerHTML=`<div class="trip-heading"><div><div class="eyebrow">YOUR SHARED ADVENTURE</div><h1>${esc(state.trip.name)}</h1><small>${state.members.filter(m=>!m.removed_at).length} friends · Balances in EUR · Recording as ${esc(actor||'Guest')}</small></div><div class="actions"><button class="ghost" id="invite-btn">Invite friends ↗</button><button id="expense-btn">+ Add expense</button></div></div><nav class="view-nav" aria-label="Trip sections">${[['expenses','Expenses'],['settlements','Settle up'],['activity','Activity']].map(([v,label])=>`<button data-view="${v}" class="${view===v?'active':''}" aria-current="${view===v?'page':'false'}">${label}</button>`).join('')}<button id="export-btn">Export CSV ↓</button></nav><div class="dashboard"><section><div class="metrics"><div><small>TOTAL SHARED EXPENSES</small><strong>${money(l.total/100)}</strong><div class="caption">${state.expenses.length} expenses, all currencies</div></div><div><small>${balance<0?'YOU OWE':balance>0?'YOU GET BACK':'YOUR BALANCE'}</small><strong>${money(Math.abs(balance)/100)}</strong><div class="caption">${balance===0?'All square. Enjoy the trip.':'After recorded settlements'}</div></div></div><div class="panel">${mainView(l)}</div></section><aside class="sidebar"><div class="panel"><div class="section-head"><h2>The group</h2><button class="secondary small-button" id="member-btn">+ Add</button></div><ul class="list">${state.members.map(m=>`<li><div class="balance-row"><span class="avatar">${esc(m.name.slice(0,2).toUpperCase())}</span><span class="person">${esc(m.name)}${m.name===actor?' <small>(you)</small>':''}</span><span class="${l.balances[m.id]>0?'positive':l.balances[m.id]<0?'negative':''}">${l.balances[m.id]>0?'+':l.balances[m.id]<0?'−':''}${money(Math.abs(l.balances[m.id])/100)}</span></div></li>`).join('')}</ul><small>Positive = gets back · Negative = owes</small></div><div class="panel"><div class="eyebrow">A NOTE FOR THE GROUP</div><h2>Keep the good times fair.</h2><p class="fine">Record each expense in its original currency. The EUR exchange rate is saved with it, so your balances won’t move tomorrow.</p><div class="divider"></div><button class="ghost small-button" id="identity-btn">Change your name</button> <button class="ghost small-button" id="leave-btn">My trips</button></div></aside></div>`;
 $('#expense-btn').onclick=()=>expense();$('#member-btn').onclick=addMember;$('#invite-btn').onclick=invite;$('#identity-btn').onclick=identity;$('#leave-btn').onclick=leave;$('#export-btn').onclick=exportData;
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>expense(state.expenses.find(e=>e.id===b.dataset.edit)));document.querySelectorAll('[data-settle]').forEach(b=>b.onclick=()=>settle(simplify(l.balances)[Number(b.dataset.settle)]));$('#manual-settle')?.addEventListener('click',()=>settle());
}
function mainViewBase(l){
 if(view==='expenses')return `<div class="section-head"><h2>Every little adventure</h2><span class="pill">${state.expenses.length} expenses</span></div>${!state.expenses.length?'<div class="empty">The best trips start with an empty ledger.<br>Add your first café, taxi or hotel expense.</div>':`<ul class="list">${state.expenses.map(e=>`<li class="expense-row"><span class="expense-icon">€</span><div class="expense-name"><b>${esc(e.description)}</b><small>${esc(state.payers.filter(p=>p.expense_id===e.id).map(p=>member(p.member_id)).join(' + '))} paid · ${esc(e.split_method)} split<br>${date(e.created_at)}</small></div><div class="expense-price"><strong>${money(Number(e.amount),e.currency)}</strong><small>${money(cents(Number(e.amount)*Number(e.exchange_rate_to_eur))/100)} total</small><br><button class="ghost small-button" data-edit="${e.id}">Edit</button></div></li>`).join('')}</ul>`}`;
 if(view==='settlements'){const transfers=simplify(l.balances);return `<div class="section-head"><h2>A simple way to settle</h2><button id="manual-settle" class="secondary small-button">Record payment</button></div><p class="fine">Suggested payments simplify the group’s debts. Record a payment only after it happens.</p>${transfers.length?transfers.map((p,i)=>`<div class="settle-row"><p><b>${esc(member(p.from))}</b> pays <b>${esc(member(p.to))}</b></p><div class="section-head"><strong>${money(p.amount/100)}</strong><button class="small-button" data-settle="${i}">Record payment</button></div></div>`).join(''):'<div class="empty">Everyone is all square. Très bien.</div>'}<h3 class="subheading">Recorded payments</h3><ul class="list">${state.settlements.map(p=>`<li><small>${date(p.created_at)}</small><p class="fine">${esc(member(p.from_member_id))} paid ${esc(member(p.to_member_id))} <b>${money(Number(p.amount_eur))}</b></p></li>`).join('')||'<li class="muted">No payments recorded yet.</li>'}</ul>`;}
 return `<div class="section-head"><h2>The shared story</h2><span class="pill">${state.activity.length} events</span></div><p class="fine">Everyone with the invite sees the same history. Names are supplied by the group, not verified identities.</p><ul class="list activity">${state.activity.map(a=>`<li><b>${esc(a.member_name||'A friend')}</b> ${esc(a.action.replaceAll('_',' '))}${a.details?.description?' · '+esc(a.details.description):a.details?.name?' · '+esc(a.details.name):''}<time>${date(a.created_at)}</time><details><summary>View full record</summary><pre>${esc(JSON.stringify(a.details,null,2))}</pre></details></li>`).join('')}</ul>`;
}
function modal(title,html){$('#modal-content').innerHTML=`<div class="dialog-head"><h2>${title}</h2><button class="close" type="button" aria-label="Close dialog">×</button></div>${html}`;$('#modal .close').onclick=()=>$('#modal').close();if(!$('#modal').open)$('#modal').showModal();}
function field(label,name,value='',attrs=''){return `<label for="${name}">${label}</label><input id="${name}" name="${name}" value="${esc(value)}" ${attrs}>`;}
function addMember(){modal('One more for Paris.',`<form id="member-form">${field('Friend’s name','name','','required maxlength="80"')}<div class="error" role="alert"></div><button class="full">Add friend</button></form>`);bindForm($('#member-form'),async(f,request_id)=>{setTrip(await api({action:'add_member',invite_code:code,actor_name:actor,name:f.get('name').trim(),request_id}));$('#modal').close();toast('Friend added to the trip');});}
function identity(){joinDialog(true);}
function invite(){const link=location.origin+location.pathname+'#'+code;modal('Paris is better together.',`<p class="fine">Send this invite to your friends. Anyone with the link can view, add and edit expenses, members and payments.</p><p class="linkbox">${esc(link)}</p><button class="full" id="copy-link">Copy invite link</button><small class="rate-note">Treat this link like the group’s password.</small>`);$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(link);toast('Invite link copied');}catch{toast('Select and copy the link above.');}};}
function expense(ex){
 if(!state.current_member_id){joinDialog();return;}
 const ps=ex?state.payers.filter(p=>p.expense_id===ex.id):[],xs=ex?state.splits.filter(p=>p.expense_id===ex.id):[];
 const expenseMembers=state.members.filter(m=>!m.removed_at||(ex&&(ps.some(p=>p.member_id===m.id)||xs.some(p=>p.member_id===m.id))));
 modal(ex?'Edit the expense.':'What did you share?',`<form id="expense-form">${field('Description','description',ex?.description||'','required maxlength="160" placeholder="Dinner in Montmartre"')}<div class="row"><div>${field('Total amount','amount',ex?.amount||'','type="number" step="0.01" min="0.01" max="1000000" required inputmode="decimal"')}</div><div><label for="currency">Currency</label><select name="currency" id="currency">${['EUR','GBP','CAD','USD'].map(c=>`<option ${c===ex?.currency?'selected':''}>${c}</option>`).join('')}</select></div></div>${field('Exchange rate · 1 original currency unit = ? EUR','rate',ex?.exchange_rate_to_eur||1,'type="number" step="0.00000001" min="0.00000001" max="1000" required inputmode="decimal"')}<div id="rate-helper" class="rate-helper"></div><small class="rate-note">Use your card’s rate or an agreed rate. This rate is saved permanently with the expense. EUR uses 1.</small><h3 class="subheading">Who paid?</h3><small>Enter each payer’s amount in the original currency. The total must match.</small>${expenseMembers.map(m=>`<div class="member-input"><input aria-label="${esc(m.name)} paid" type="checkbox" name="paid-${m.id}" ${ps.some(p=>p.member_id===m.id)||(!ex&&m.name===actor)?'checked':''}><label for="pay-${m.id}">${esc(m.name)}</label><input id="pay-${m.id}" aria-label="Amount paid by ${esc(m.name)}" name="pay-${m.id}" type="number" min="0" step="0.01" inputmode="decimal" value="${esc(ps.find(p=>p.member_id===m.id)?.amount||'')}"></div>`).join('')}<h3 class="subheading">How should we split it?</h3><label for="split">Split method</label><select id="split" name="split">${[['equal','Equally'],['shares','By shares (e.g. 2 : 1 : 1)'],['percentage','By percentage'],['exact','Exact amounts']].map(([v,l])=>`<option value="${v}" ${ex?.split_method===v?'selected':''}>${l}</option>`).join('')}</select>${expenseMembers.map(m=>`<div class="member-input"><input aria-label="Include ${esc(m.name)}" type="checkbox" name="include-${m.id}" ${!ex||xs.some(x=>x.member_id===m.id)?'checked':''}><label for="share-${m.id}">${esc(m.name)}</label><input id="share-${m.id}" aria-label="Split value for ${esc(m.name)}" name="share-${m.id}" type="number" min="0" step="0.0001" inputmode="decimal" value="${esc(xs.find(x=>x.member_id===m.id)?.value??1)}"></div>`).join('')}<div class="error" role="alert"></div><button class="full">${ex?'Save changes':'Save expense'}</button></form>`);
 const splitInputs=()=>document.querySelectorAll('[id^=share-]').forEach(i=>{i.disabled=$('#split').value==='equal'});splitInputs();$('#split').onchange=splitInputs;
 const rateInput=()=>{if($('#currency').value==='EUR'){$('#rate').value=1;$('#rate').readOnly=true;}else{$('#rate').readOnly=false;if(!ex)$('#rate').value='';}};rateInput();$('#currency').onchange=rateInput;
 installRateHelper(ex);
 $('#amount').oninput=()=>{const checked=state.members.filter(m=>$(`[name="paid-${m.id}"]`).checked);if(checked.length===1)$(`[name="pay-${checked[0].id}"]`).value=$('#amount').value;};
 bindForm($('#expense-form'),async(f,request_id)=>{
 const payers=state.members.filter(m=>f.has('paid-'+m.id)).map(m=>({member_id:m.id,amount:Number(f.get('pay-'+m.id))}));const participants=state.members.filter(m=>f.has('include-'+m.id)).map(m=>({member_id:m.id,value:f.get('split')==='equal'?1:Number(f.get('share-'+m.id))}));
 if(!payers.length||!participants.length)throw Error('Choose at least one payer and participant.');if(payers.reduce((n,p)=>n+cents(p.amount),0)!==cents(f.get('amount')))throw Error('Payer amounts must equal the expense total.');
 const payload={action:ex?'edit_expense':'add_expense',invite_code:code,actor_name:actor,request_id,description:f.get('description').trim(),amount:Number(f.get('amount')),currency:f.get('currency'),exchange_rate_to_eur:Number(f.get('rate')),split_method:f.get('split'),payers,participants};payload.rate_source=$('#rate').dataset.source||'Custom rate';payload.rate_date=$('#rate').dataset.date||null;if(ex)Object.assign(payload,{expense_id:ex.id,expected_updated_at:ex.updated_at});
 setTrip(await api(payload));$('#modal').close();toast(ex?'Expense updated. Previous details are in Activity.':'Expense shared with the group');
 });
}
function settle(p){if(state.members.length<2){toast('Add another friend first.');return;}modal('Record a payment.',`<p class="fine">This records money already paid between friends. It does not send money.</p><form id="settle-form"><label for="from">Paid by</label><select id="from" name="from">${state.members.map(m=>`<option value="${m.id}" ${m.id===p?.from?'selected':''}>${esc(m.name)}</option>`).join('')}</select><label for="to">Paid to</label><select id="to" name="to">${state.members.map((m,i)=>`<option value="${m.id}" ${m.id===p?.to||(!p&&i===1)?'selected':''}>${esc(m.name)}</option>`).join('')}</select>${field('Amount paid in EUR','amount',p?(p.amount/100).toFixed(2):'','type="number" step="0.01" min="0.01" max="1000000" required inputmode="decimal"')}<div class="error" role="alert"></div><button class="full">Record this payment</button></form>`);bindForm($('#settle-form'),async(f,request_id)=>{setTrip(await api({action:'settle',invite_code:code,actor_name:actor,request_id,from_member_id:f.get('from'),to_member_id:f.get('to'),amount_eur:Number(f.get('amount'))}));$('#modal').close();toast('Payment recorded');});}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([tripCsv(state)],{type:'text/csv;charset=utf-8'}));a.download=state.trip.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'-expenses.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('CSV exported with expenses, payments, balances and activity');}
function leave(){epoch++;state=null;code='';actor='';storage.remove('paris-code');history.replaceState(null,'',location.pathname);clearTimeout(reconnect);clearInterval(heartbeat);if(ws){ws.onclose=null;ws.close();}connection('Ready for Paris');welcome();}
async function boot(){welcome();const saved=location.hash.slice(1)||storage.get('paris-code');if(saved)await openTrip(saved);}


function trips(){try{return JSON.parse(storage.get('paris-trips')||'[]')}catch{return []}}
function saveTrip(record){const all=trips().filter(t=>t.id!==record.id);storage.set('paris-trips',JSON.stringify([record,...all]));}
async function api(payload){
 const record=trips().find(t=>t.code===payload.invite_code);
 const p={...payload};
 if(record){if(!['create_trip','join_trip'].includes(p.action)&&record.session)p.session_token=record.session;if(record.owner&&!p.owner_key)p.owner_key=record.owner;}
 return transport(p);
}
function welcome(){welcomeBase();
 const saved=trips();if(saved.length){const block=document.createElement('section');block.className='saved-trips';block.innerHTML='<div class="section-head"><h2>Your trips</h2><small>Saved on this device</small></div><div class="trip-cards">'+saved.map(t=>'<button class="trip-card" data-trip="'+esc(t.id)+'"><span>'+esc(t.name)+'</span><small>'+esc(t.actor||'Join this trip')+' →</small></button>').join('')+'</div>';$('#app').prepend(block);block.querySelectorAll('[data-trip]').forEach(b=>b.onclick=()=>openTrip(saved.find(t=>t.id===b.dataset.trip).code));}
 if(mode==='join'){const f=$('#welcome-form'),input=$('#your-name'),label=f.querySelector('label[for="your-name"]');f.prepend(label,input);}
}
async function openTrip(inviteCode){
 epoch++;const token=epoch;connection('Opening your trip…');
 clearTimeout(reconnect);clearInterval(heartbeat);if(ws){ws.onclose=null;ws.close();}state=null;$('#app').innerHTML='<div class="empty">Opening your trip…</div>';
 try{const next=await api({action:'get_trip',invite_code:parseCode(inviteCode)});if(token!==epoch)return;setTrip(next);live();if(!state.current_member_id)joinDialog();}
 catch(e){if(/reset/i.test(e.message)){storage.set('paris-trips',JSON.stringify(trips().filter(t=>t.code!==inviteCode)));storage.remove('paris-code');history.replaceState(null,'',location.pathname);}state=null;connection('Ready for Paris');welcome();toast(e.message);}
}
function render(){renderBase();if(!state)return;
 const nav=$('.view-nav'),switcher=document.createElement('button');switcher.textContent='My trips ↗';switcher.id='trips-btn';switcher.onclick=tripSwitcher;nav.prepend(switcher);
 $('#leave-btn').onclick=tripSwitcher;
 $('#expense-btn').onclick=()=>state.current_member_id?expense():joinDialog();$('#member-btn').onclick=()=>state.current_member_id?addMember():joinDialog();
 document.querySelectorAll('[data-edit]').forEach(b=>{const del=document.createElement('button');del.className='ghost small-button danger';del.textContent='Delete';del.setAttribute('aria-label','Delete '+state.expenses.find(e=>e.id===b.dataset.edit).description);del.onclick=()=>deleteExpense(state.expenses.find(e=>e.id===b.dataset.edit));b.after(del);});
 const panel=$('.sidebar .panel');state.members.forEach((m,i)=>{if(m.removed_at){const label=panel.querySelectorAll('.person')[i];label.insertAdjacentHTML('beforeend',' <small>(removed)</small>');}});
 if(state.is_creator){const manage=document.createElement('button');manage.className='secondary full';manage.id='manage-members';manage.textContent='Manage members';manage.onclick=manageMembers;panel.append(manage);}
 const rates=document.createElement('div');rates.className='panel';rates.innerHTML='<div class="eyebrow">LATEST PUBLISHED RATES</div><h2>A quick currency check.</h2><div id="rates-widget"><small>Loading daily rates…</small></div>';
 $('.sidebar').append(rates);showRates();
 document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>restoreExpense(state.deleted_expenses.find(e=>e.id===b.dataset.restore)));
}
function tripSwitcher(){modal('Your trips.', '<p class="fine">Each trip has its own people, expenses and invite. These trips are saved on this device.</p><div class="trip-cards">'+trips().map(t=>'<button class="trip-card" data-switch="'+esc(t.id)+'"><span>'+esc(t.name)+'</span><small>'+esc(t.actor||'Open')+(t.id===state?.trip.id?' · Current':' →')+'</small></button>').join('')+'</div><div class="row"><button class="full" id="new-trip">+ New trip</button><button class="full secondary" id="join-trip">Join another</button></div>');document.querySelectorAll('[data-switch]').forEach(b=>b.onclick=()=>{$('#modal').close();openTrip(trips().find(t=>t.id===b.dataset.switch).code);});$('#new-trip').onclick=()=>{$('#modal').close();mode='create';leave();};$('#join-trip').onclick=()=>{$('#modal').close();mode='join';leave();};}
function joinDialog(changing=false){
 const group=state.members.filter(m=>!m.removed_at);
 modal(changing?'Choose your name.':'Welcome to '+esc(state.trip.name)+'.', '<form id="join-name"><label for="joining-name">Your name</label><input id="joining-name" name="name" required maxlength="80" autocomplete="given-name" placeholder="What should we call you?" autofocus><div class="error" role="alert"></div><button class="full">'+(changing?'Use this name':'Join this trip')+'</button></form><h3 class="subheading">Already in the group?</h3><p class="fine">If a friend already added you, choose your name below.</p><div class="member-pills">'+group.map(m=>'<button class="secondary small-button" data-join-name="'+esc(m.id)+'">'+esc(m.name)+'</button>').join('')+'</div><button class="ghost small-button recovery-link" id="recover-creator">Restore creator access</button>');
 bindForm($('#join-name'),async(f,request_id)=>{setTrip(await api({action:'join_trip',invite_code:code,name:f.get('name').trim(),request_id}));$('#modal').close();live();});
 document.querySelectorAll('[data-join-name]').forEach(b=>b.onclick=()=>{$('#joining-name').value=group.find(m=>m.id===b.dataset.joinName).name;$('#join-name').requestSubmit();});$('#recover-creator').onclick=recoverCreator;
}
function activityDetails(a){const d=a.details||{};let html='';
 const item=(label,value)=>'<div class="record-row"><dt>'+esc(label)+'</dt><dd>'+esc(value)+'</dd></div>';
 const expenseDetails=(e,title)=>{let h='<h4>'+title+'</h4><dl>'+item('Description',e.description||'Expense')+item('Amount',money(Number(e.amount||0),e.currency||'EUR'));
 if(e.exchange_rate_to_eur)h+=item('Saved rate','1 '+e.currency+' = '+Number(e.exchange_rate_to_eur)+' EUR');
 if(e.rate_date)h+=item('Rate date',e.rate_date);if(e.rate_source)h+=item('Rate source',e.rate_source);
 h+=item('Split',({equal:'Equally',shares:'By shares',percentage:'By percentage',exact:'Exact amounts'})[e.split_method]||e.split_method||'Recorded in original expense');
 if(e.payers?.length)h+=item('Paid by',e.payers.map(p=>member(p.member_id)+' — '+money(Number(p.amount),e.currency||'EUR')).join('; '));
 if(e.participants?.length)h+=item('Split between',e.participants.map(p=>member(p.member_id)+(e.split_method==='equal'?'':': '+p.value+(e.split_method==='percentage'?'%':e.split_method==='exact'?' '+e.currency:' shares'))).join('; '));
 return h+'</dl>';};
 if(d.before)html+=expenseDetails(d.before,a.action==='edited_expense'?'Before the edit':'Original expense');
 if(d.description&&a.action!=='deleted_expense'&&a.action!=='restored_expense')html+=expenseDetails(d,d.before?'After the edit':'Expense details');
 if(a.action==='recorded_settlement')html+='<dl>'+item('Paid by',member(d.from_member_id))+item('Paid to',member(d.to_member_id))+item('Amount',money(Number(d.amount_eur)))+'</dl>';
 if(!html)html='<dl>'+item('What happened',activitySummary(a,state))+'</dl>';
 return html+'<dl>'+item('Recorded by',a.member_name||'A friend')+item('When',date(a.created_at))+'</dl>';
}
function mainView(l){if(view!=='activity')return mainViewBase(l);
 const removed=state.deleted_expenses||[];
 return '<div class="section-head"><h2>The shared story</h2><span class="pill">'+state.activity.length+' events</span></div><p class="fine">A readable history of who changed what. Deleted expenses remain here and can be restored.</p>'+(removed.length?'<details class="deleted-list"><summary>Deleted expenses ('+removed.length+')</summary>'+removed.map(e=>'<div class="section-head"><span>'+esc(e.description)+' · '+money(Number(e.amount),e.currency)+'</span><button class="secondary small-button" data-restore="'+e.id+'">Restore</button></div>').join('')+'</details>':'')+'<ul class="list activity">'+state.activity.map(a=>'<li><b>'+esc(a.member_name||'A friend')+'</b><p class="fine">'+esc(activitySummary(a,state))+'</p><time>'+date(a.created_at)+'</time><details><summary>View full record</summary><div class="record">'+activityDetails(a)+'</div></details></li>').join('')+'</ul>';
}
function deleteExpense(ex){if(!state.current_member_id){joinDialog();return;}modal('Delete this expense?', '<p class="fine"><b>'+esc(ex.description)+'</b> — '+money(Number(ex.amount),ex.currency)+' will be removed from everyone’s balances. Its history stays in Activity, where it can be restored.</p><form id="delete-form"><div class="error" role="alert"></div><button class="full danger-button">Delete expense</button></form>');bindForm($('#delete-form'),async(f,request_id)=>{setTrip(await api({action:'delete_expense',invite_code:code,expense_id:ex.id,expected_updated_at:ex.updated_at,request_id}));$('#modal').close();toast('Expense deleted. You can restore it in Activity.');});}
function restoreExpense(ex){modal('Restore this expense?', '<p class="fine">'+esc(ex.description)+' will count toward everyone’s balances again.</p><form id="restore-form"><div class="error" role="alert"></div><button class="full">Restore expense</button></form>');bindForm($('#restore-form'),async(f,request_id)=>{setTrip(await api({action:'restore_expense',invite_code:code,expense_id:ex.id,expected_updated_at:ex.updated_at,request_id}));$('#modal').close();toast('Expense restored');});}
function manageMembers(){modal('Creator controls.', '<p class="fine">Removing a member keeps past expenses and balances, revokes their saved access, and replaces the invite link. Other joined friends keep access. To invite someone new afterwards, share the updated link.</p><ul class="list">'+state.members.map(m=>'<li><div class="section-head"><span>'+esc(m.name)+(m.id===state.creator_member_id?' · Creator':m.removed_at?' · Removed':'')+'</span>'+(m.id===state.creator_member_id?'':'<button class="ghost small-button" data-manage-member="'+m.id+'">'+(m.removed_at?'Restore':'Remove')+'</button>')+'</div></li>').join('')+'</ul><div class="divider"></div><button class="secondary full" id="creator-key">Save creator recovery key</button><p class="fine">Keep the recovery key private. It restores creator controls on another device.</p>');document.querySelectorAll('[data-manage-member]').forEach(b=>b.onclick=()=>memberAction(state.members.find(m=>m.id===b.dataset.manageMember)));$('#creator-key').onclick=()=>{const key=trips().find(t=>t.id===state.trip.id)?.owner;modal('Your creator recovery key.', '<p class="fine">Save this privately with your trip invite. Never include it in your group’s invite message.</p><p class="linkbox">'+esc(key)+'</p><button class="full" id="copy-owner">Copy recovery key</button>');$('#copy-owner').onclick=async()=>{try{await navigator.clipboard.writeText(key);toast('Creator recovery key copied');}catch{toast('Select and copy the key above.');}};};}
function memberAction(m){const restore=!!m.removed_at;modal((restore?'Restore ':'Remove ')+esc(m.name)+'?', '<p class="fine">'+(restore?'They can join again using the current invite.':'Their previous expenses and balances stay visible. Their access will be revoked, and the old invite link will stop working.')+'</p><form id="member-action"><div class="error" role="alert"></div><button class="full">'+(restore?'Restore member':'Remove member')+'</button></form>');bindForm($('#member-action'),async(f,request_id)=>{setTrip(await api({action:restore?'restore_member':'remove_member',invite_code:code,member_id:m.id,request_id}));$('#modal').close();toast(restore?'Member restored':'Member removed. Use Invite friends for the new link.');});}
function recoverCreator(){modal('Restore creator access.', '<form id="recover-form">'+field('Creator recovery key','owner-key','','required autocomplete="off"')+'<div class="error" role="alert"></div><button class="full">Restore my access</button></form>');bindForm($('#recover-form'),async(f)=>{const owner=f.get('owner-key').trim();const next=await api({action:'restore_creator',invite_code:code,owner_key:owner});next.owner_key=owner;setTrip(next);$('#modal').close();toast('Creator access restored');});}
let ratesPromise=null;
function getRates(){if(!ratesPromise)ratesPromise=fetch('https://api.frankfurter.dev/v2/rates?base=EUR&quotes=GBP,CAD,USD&providers=ecb',{signal:AbortSignal.timeout(10000)}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(rows=>{if(!Array.isArray(rows)||rows.length!==3||rows.some(r=>!Number.isFinite(r.rate)||r.rate<=0))throw Error();return rows;}).catch(e=>{ratesPromise=null;throw e;});return ratesPromise;}
async function showRates(){try{const rows=await getRates();const box=$('#rates-widget');if(box)box.innerHTML='<ul class="list">'+rows.map(r=>'<li class="section-head"><span>1 EUR → '+esc(r.quote)+'</span><b>'+Number(r.rate).toFixed(4)+'</b></li>').join('')+'</ul><small>ECB via Frankfurter · '+esc(rows[0].date)+'<br>Daily reference rates, not your card’s live rate.</small>';}catch{const box=$('#rates-widget');if(box)box.innerHTML='<small>Rates are unavailable right now. You can still enter your own rate when adding an expense.</small>';}}
function installRateHelper(ex){const input=$('#rate'),box=$('#rate-helper');input.addEventListener('input',()=>{delete input.dataset.source;delete input.dataset.date;});const update=async()=>{const currency=$('#currency').value;box.innerHTML='';if(currency==='EUR')return;box.innerHTML='<small>Loading latest '+esc(currency)+' → EUR rate…</small>';try{const rows=await getRates();if(!$('#currency')||$('#currency').value!==currency)return;const row=rows.find(r=>r.quote===currency),rate=Number((1/row.rate).toFixed(8));box.innerHTML='<small>Latest published: 1 '+esc(currency)+' = '+rate+' EUR<br>ECB · '+esc(row.date)+'</small><button type="button" class="secondary small-button" id="use-rate">Use this rate</button>';$('#use-rate').onclick=()=>{input.value=rate;input.dataset.source='ECB via Frankfurter';input.dataset.date=row.date;};}catch{box.innerHTML='<small>Latest rates unavailable. Enter your card’s rate or an agreed rate.</small>';}};$('#currency').addEventListener('change',()=>{delete input.dataset.source;delete input.dataset.date;update();});update();}
boot();
