import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';import {ledger} from '../money.js';import {tripCsv} from '../formats.js';
const root='https://rxzaoeolvaoafzhofcco.supabase.co',url=root+'/functions/v1/paris-split-api';
async function send(p,ok=true){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();if(ok)assert.equal(r.status,200,JSON.stringify(d));else assert.notEqual(r.status,200);return d;}
const id=()=>crypto.randomUUID();const health=await(await fetch(url)).json();assert.equal(health.version,'3.0.0');
const creation={action:'create_trip',name:'Feature QA Paris',member_name:'Alice',request_id:id()};let a=await send(creation);const own=a.owner_key,at=a.session_token,aid=a.current_member_id,invite=a.trip.invite_code;assert.ok(own&&at&&a.is_creator);assert.equal((await send(creation)).owner_key,own);console.log('PASS creator key, member session and create retry');
const b=await send({action:'join_trip',invite_code:invite,name:'Bob',request_id:id()}),bt=b.session_token,bid=b.current_member_id;assert.ok(bt&&!b.is_creator&&!b.owner_key);
const c=await send({action:'join_trip',invite_code:invite,name:'Carol',request_id:id()}),ct=c.session_token,cid=c.current_member_id;
await send({action:'remove_member',session_token:bt,member_id:cid,request_id:id()},false);await send({action:'remove_member',session_token:bt,owner_key:'wrong',member_id:cid,request_id:id()},false);await send({action:'restore_creator',invite_code:invite},false);console.log('PASS missing or wrong owner credentials cannot manage members');
const expense={action:'add_expense',session_token:at,actor_name:'Fake actor',request_id:id(),description:'Café, "Paris"',amount:120,currency:'EUR',exchange_rate_to_eur:1,split_method:'exact',payers:[{member_id:aid,amount:100},{member_id:bid,amount:20}],participants:[{member_id:aid,value:30},{member_id:bid,value:40},{member_id:cid,value:50}]};
a=await send(expense);assert.deepEqual(ledger(a).balances,{[aid]:7000,[bid]:-2000,[cid]:-5000});assert.equal(a.activity[0].member_name,'Alice');const ex=a.expenses[0];
const del={action:'delete_expense',session_token:at,expense_id:ex.id,expected_updated_at:ex.updated_at,request_id:id()};a=await send(del);assert.equal(a.expenses.length,0);assert.equal(a.deleted_expenses.length,1);assert.equal(ledger(a).total,0);a=await send(del);assert.equal(a.activity.filter(x=>x.action==='deleted_expense').length,1);a=await send({action:'restore_expense',session_token:at,expense_id:ex.id,expected_updated_at:a.deleted_expenses[0].updated_at,request_id:id()});assert.equal(a.expenses.length,1);assert.equal(ledger(a).total,12000);console.log('PASS delete, restore, cent totals and audit history');
const csv=tripCsv(a);assert.ok(csv.includes('"Café, ""Paris"""'));assert.ok(!csv.includes(own)&&!csv.includes(at)&&!csv.includes(invite));
a=await send({action:'remove_member',session_token:at,owner_key:own,member_id:bid,request_id:id()});assert.notEqual(a.trip.invite_code,invite);assert.ok(a.members.find(m=>m.id===bid).removed_at);assert.deepEqual(ledger(a).balances,{[aid]:7000,[bid]:-2000,[cid]:-5000});
await send({action:'get_trip',session_token:bt},false);await send({action:'get_trip',invite_code:invite},false);const still=await send({action:'get_trip',session_token:ct});assert.equal(still.trip.id,a.trip.id);assert.ok(!still.owner_key&&!still.session_token&&!still.is_creator);console.log('PASS removal revokes member and old invite, preserves other sessions and historical balances');
await send({...expense,request_id:id()},false);a=await send({action:'restore_member',session_token:at,owner_key:own,member_id:bid,request_id:id()});assert.ok(!a.members.find(m=>m.id===bid).removed_at);const rejoin=await send({action:'join_trip',invite_code:a.trip.invite_code,name:'Bob',request_id:id()});assert.equal(rejoin.current_member_id,bid);assert.notEqual(rejoin.session_token,bt);console.log('PASS restored member rejoins without duplicate identity');
const recovered=await send({action:'restore_creator',invite_code:a.trip.invite_code,owner_key:own});assert.ok(recovered.is_creator&&recovered.session_token);assert.equal(recovered.current_member_id,aid);console.log('PASS creator recovery from a new session');
const other=await send({action:'create_trip',name:'Feature QA London',member_name:'Dan',request_id:id()});assert.equal(other.expenses.length,0);await send({...expense,session_token:other.session_token,request_id:id()},false);assert.equal((await send({action:'get_trip',session_token:at})).expenses.length,1);console.log('PASS multiple trips stay isolated');
const auth={apikey:health.anonKey,Authorization:'Bearer '+health.anonKey};for(const table of ['trips','members','expenses','expense_payers','expense_splits','settlements','activity_log','paris_creators','paris_sessions','paris_v3_requests','paris_rate_limits']){const r=await fetch(root+'/rest/v1/'+table+'?select=*',{headers:auth});const d=await r.json();assert.ok(!r.ok||(Array.isArray(d)&&d.length===0),table+' leaked');}
const rpc=await fetch(root+'/rest/v1/rpc/paris_split_v3',{method:'POST',headers:{...auth,'Content-Type':'application/json'},body:JSON.stringify({payload:{action:'get_trip',session_token:at}})});assert.notEqual(rpc.status,200);console.log('PASS private keys, sessions and database RPC remain inaccessible to anonymous clients');
const rates=await(await fetch('https://api.frankfurter.dev/v2/rates?base=EUR&quotes=GBP,CAD,USD&providers=ecb')).json();assert.equal(rates.length,3);assert.ok(rates.every(r=>r.rate>0&&r.date));console.log('PASS current dated ECB rates for GBP, CAD and USD');
await mkdir('work',{recursive:true});await writeFile('work/features-qa.json',JSON.stringify({trip:a.trip.id,code:a.trip.invite_code,session:at,owner:own}));console.log('All feature API checks passed.');
